# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 12:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans', models.CharField(max_length=10000)),
                ('ans_author', models.CharField(max_length=30)),
                ('ans_date', models.DateTimeField(blank=True, default=datetime.datetime(2016, 6, 21, 12, 27, 54, 715071))),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.CharField(max_length=10000)),
                ('ques_author', models.CharField(max_length=30)),
                ('ques_date', models.DateTimeField(blank=True, default=datetime.datetime(2016, 6, 21, 12, 27, 54, 708094))),
            ],
        ),
        migrations.AddField(
            model_name='answere',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Question'),
        ),
    ]
