# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 17:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20160621_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='ans_author',
            field=models.CharField(editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='answer',
            name='ans_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 6, 24, 23, 26, 0, 355050)),
        ),
        migrations.AlterField(
            model_name='question',
            name='ques_author',
            field=models.CharField(editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='question',
            name='ques_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 6, 24, 23, 26, 0, 338670)),
        ),
    ]
