# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 17:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20160624_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='ans_author',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='answer',
            name='ans_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 6, 24, 23, 29, 36, 741638)),
        ),
        migrations.AlterField(
            model_name='question',
            name='ques_author',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='question',
            name='ques_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 6, 24, 23, 29, 36, 734429)),
        ),
    ]
