# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 06:23
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0004_auto_20160624_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='answer',
            name='ans_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 7, 10, 11, 53, 57, 126836)),
        ),
        migrations.AlterField(
            model_name='question',
            name='ques_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 7, 10, 11, 53, 57, 126309)),
        ),
    ]
