# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 06:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_auto_20160710_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='answer',
            name='ans_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 7, 10, 12, 7, 26, 209083)),
        ),
        migrations.AlterField(
            model_name='question',
            name='ques_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 7, 10, 12, 7, 26, 192076)),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
